### ISSUE TITLE
onRatingChanged called allways

### ISSUE THREAD

**Issue by klaszlo8207** [thangmam/smoothratingbar#12]
Any way to call  a listener only when we 'touch up' on a star?

**Comment by thangmam** [comment]
hello , onRatingChanged will be called whenever its tapped/dragged on the SmoothRatingStar widget which is needed to rebuild the widget so that we can see the visual changes on the widget.If you can explain your requirement a bit more detail, i will try my best to help out.Thanks

**Comment by klaszlo8207** [comment]
I ended up with a rxdart debounce operator, thanks

**Comment by thangmam** [comment]
okay, i will close this issue for now.Feel free to open again if needed.Thanks for the feedback anyway
