### ISSUE TITLE
Half ratings are not 0.5 increments

### ISSUE THREAD

**Issue by WanderingFire2001** [thangmam/smoothratingbar#22]
If a user gesture drags to set a rating and 1/2 ratings are enabled, the value reported is some double between the whole number indexes they've selected. It would be more expected to return 0.0, 0.5, 1.0, 1.5, 2.0, 2.5, ...  No one can accurately gesture drag more precisely, and the widget displays half values, but the reported value may be 2.2478 when the user expected they were setting the value 2.5.

It would just take a small bit of rounding logic on:
https://github.com/thangmam/smoothratingbar/blob/master/lib/smooth_star_rating.dart#L68

Thanks for the simple, clean rating widget!

**Comment by thangmam** [comment]
@WanderingFire2001 I have fixed this.Please checkout the new update 
[https://pub.dev/packages/smooth_star_rating
](url)
