### ISSUE TITLE
Unexpected behavior on web ?

### ISSUE THREAD

**Issue by Nanodash** [thangmam/smoothratingbar#24]
Hello @thangmam ! 😄 
Thank for this simple and straightforward widget :)

I just imported it in a web project and the behavior of this package feels weird... The user **with a mouse** is expecting the widget to react on hovering !

![rL6rweuvRZ](https://user-images.githubusercontent.com/61005635/76153768-4c22c580-60d1-11ea-92f8-83852dd2668f.gif)

This may have been **totally normal** when having mobile device in mind while developing your widget, but you may want to change it so it reacts on mouse hovering **only on web** platforms and maybe even desktop OS !

I will post a PR to work on it 👍 

Regards,
NanoDash 🎯

**Comment by thangmam** [comment]
@NanoDashDev hi, i have accepted your PR and also made a few modifications.Check out and let me know if there are bugs.Thanks for PR
[https://pub.dev/packages/smooth_star_rating
](url)
