### ISSUE TITLE
Support right-to-left locales

### ISSUE THREAD

**Issue by Skyost** [thangmam/smoothratingbar#28]
Hi !

My package ([RateMyApp](https://github.com/Skyost/RateMyApp)) depends on yours in order to display a star rate dialog. But I have problems with users who are using right-to-left locales. Would it be possible to add a support for it in this plugin ?

It would be great !

**Comment by thangmam** [comment]
Hi , i will look into it when i get the time but i cant say exactly when i can push the changes but probably by this months end i will try to implement it. Thanks for using this plugin.

**Comment by Skyost** [comment]
Top. Thank you !
