### ISSUE TITLE
Star colors aren't updated

### ISSUE THREAD

**Issue by alexxgarci** [thangmam/smoothratingbar#3]
When calling GestureDetector, the starts don't fill with any color. Seen in Android.

**Comment by jeeali** [comment]
same here

**Comment by thangmam** [comment]
hello , could you describe the issue in details. @alexxgarci What do you mean calling GestureDetector.Are you wraping the smooth_star_rating widget with another widget ? 

@alexxgarci  @jeeali Guys, show me the code so that i can replicate the issue.Thanks

**Comment by rshrc** [comment]
Hey @thangmam I need to use this widget for a project, I've used this inside a AlertDialog->Column->SmoothStarRating.. the color of the widget is not being updated as I think it is not able to detect gesture
I've attached the code here which will help you reproduce the error 
https://pastebin.com/Pph9N8H7

**Comment by thangmam** [comment]
@rshrc hello ,try putting your alert dialog in a separate stateful widget.This way it will be able to handle the state update independently.Something like this 

>  showDialog(
            context: context,
            builder: (_) {
              return MyDialog();//your stateful widget for dialog here
            })

>

**Comment by rshrc** [comment]
> @rshrc hello ,try putting your alert dialog in a separate stateful widget.This way it will be able to handle the state update independently.Something like this
> 
> > showDialog(
> > context: context,
> > builder: (_) {
> > return MyDialog();//your stateful widget for dialog here
> > })
> 
> >

Ah, I see @thangmam this is one approach that did not cross my mind. Thank you, will get back to you once this starts working

**Comment by thangmam** [comment]
okay

**Comment by thangmam** [comment]
Closing this issue for now since i didnt get any response.Dont hesitate to open again.Thanks
